create table if not exists public.users (
  email text primary key,
  password text not null,
  role text not null default 'crs',
  fullname text not null,
  position text not null,
  branchid text default '',
  first_login boolean not null default true,
  must_change_password boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.users add column if not exists password text;
alter table public.users add column if not exists role text default 'crs';
alter table public.users add column if not exists fullname text;
alter table public.users add column if not exists position text;
alter table public.users add column if not exists branchid text default '';
alter table public.users add column if not exists first_login boolean default true;
alter table public.users add column if not exists must_change_password boolean default true;
alter table public.users add column if not exists created_at timestamptz default now();
alter table public.users add column if not exists updated_at timestamptz default now();

create table if not exists public.members (
  member_id text primary key,
  full_name text not null,
  address text default '',
  contact_number text default '',
  branch text default '',
  segmentation text default '',
  gender text default '',
  status text default 'Active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.members add column if not exists member_id text;
alter table public.members add column if not exists full_name text;
alter table public.members add column if not exists address text default '';
alter table public.members add column if not exists contact_number text default '';
alter table public.members add column if not exists branch text default '';
alter table public.members add column if not exists segmentation text default '';
alter table public.members add column if not exists gender text default '';
alter table public.members add column if not exists status text default 'Active';
alter table public.members add column if not exists created_at timestamptz default now();
alter table public.members add column if not exists updated_at timestamptz default now();

create table if not exists public.hospitals (
  id bigint generated by default as identity primary key,
  name text not null,
  address text default '',
  contact_number text default '',
  status text default 'Active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.hospitals add column if not exists name text;
alter table public.hospitals add column if not exists address text default '';
alter table public.hospitals add column if not exists contact_number text default '';
alter table public.hospitals add column if not exists status text default 'Active';
alter table public.hospitals add column if not exists created_at timestamptz default now();
alter table public.hospitals add column if not exists updated_at timestamptz default now();

create table if not exists public.segmentation_rates (
  segmentation text primary key,
  daily_rate numeric(14, 2) not null default 0,
  description text default '',
  updated_at timestamptz not null default now()
);

alter table public.segmentation_rates add column if not exists segmentation text;
alter table public.segmentation_rates add column if not exists daily_rate numeric(14, 2) default 0;
alter table public.segmentation_rates add column if not exists description text default '';
alter table public.segmentation_rates add column if not exists updated_at timestamptz default now();

create table if not exists public.hospitalizationclaims (
  claim_id text primary key,
  date_filed timestamptz not null default now(),
  member_id text not null references public.members(member_id) on delete restrict,
  member_name text not null,
  contact_number text default '',
  branch text default '',
  segmentation text default '',
  hospital_id bigint references public.hospitals(id) on delete restrict,
  hospital_name text default '',
  date_admitted date not null,
  date_discharged date not null,
  actual_days_confined integer not null default 0,
  days_confined integer not null default 0,
  daily_rate numeric(14, 2) not null default 0,
  claimable_amount numeric(14, 2) not null default 0,
  days_approved integer not null default 0,
  amount_approved numeric(14, 2) not null default 0,
  diagnosis text default '',
  claim_year integer not null,
  claim_status text not null default 'Pending',
  status text not null default 'Pending',
  gender text default '',
  encoded_by text default '',
  encoder_e_sign text default '',
  processed_by text default '',
  processor_e_sign text default '',
  checked_by text default '',
  checker_e_sign text default '',
  finance_checked_by text default '',
  approved_by text default '',
  approver_e_sign text default '',
  denied_by text default '',
  remarks text default '',
  last_updated timestamptz not null default now(),
  payment_date date,
  last_updated_by text default ''
);

alter table public.hospitalizationclaims add column if not exists claim_id text;
alter table public.hospitalizationclaims add column if not exists date_filed timestamptz default now();
alter table public.hospitalizationclaims add column if not exists member_id text;
alter table public.hospitalizationclaims add column if not exists member_name text;
alter table public.hospitalizationclaims add column if not exists contact_number text default '';
alter table public.hospitalizationclaims add column if not exists branch text default '';
alter table public.hospitalizationclaims add column if not exists segmentation text default '';
alter table public.hospitalizationclaims add column if not exists hospital_id bigint;
alter table public.hospitalizationclaims add column if not exists hospital_name text default '';
alter table public.hospitalizationclaims add column if not exists date_admitted date;
alter table public.hospitalizationclaims add column if not exists date_discharged date;
alter table public.hospitalizationclaims add column if not exists actual_days_confined integer default 0;
alter table public.hospitalizationclaims add column if not exists days_confined integer default 0;
alter table public.hospitalizationclaims add column if not exists daily_rate numeric(14, 2) default 0;
alter table public.hospitalizationclaims add column if not exists claimable_amount numeric(14, 2) default 0;
alter table public.hospitalizationclaims add column if not exists days_approved integer default 0;
alter table public.hospitalizationclaims add column if not exists amount_approved numeric(14, 2) default 0;
alter table public.hospitalizationclaims add column if not exists diagnosis text default '';
alter table public.hospitalizationclaims add column if not exists claim_year integer;
alter table public.hospitalizationclaims add column if not exists claim_status text default 'Pending';
alter table public.hospitalizationclaims add column if not exists status text default 'Pending';
alter table public.hospitalizationclaims add column if not exists gender text default '';
alter table public.hospitalizationclaims add column if not exists encoded_by text default '';
alter table public.hospitalizationclaims add column if not exists encoder_e_sign text default '';
alter table public.hospitalizationclaims add column if not exists processed_by text default '';
alter table public.hospitalizationclaims add column if not exists processor_e_sign text default '';
alter table public.hospitalizationclaims add column if not exists checked_by text default '';
alter table public.hospitalizationclaims add column if not exists checker_e_sign text default '';
alter table public.hospitalizationclaims add column if not exists finance_checked_by text default '';
alter table public.hospitalizationclaims add column if not exists approved_by text default '';
alter table public.hospitalizationclaims add column if not exists approver_e_sign text default '';
alter table public.hospitalizationclaims add column if not exists denied_by text default '';
alter table public.hospitalizationclaims add column if not exists remarks text default '';
alter table public.hospitalizationclaims add column if not exists last_updated timestamptz default now();
alter table public.hospitalizationclaims add column if not exists payment_date date;
alter table public.hospitalizationclaims add column if not exists last_updated_by text default '';

create index if not exists hospitalizationclaims_status_idx
  on public.hospitalizationclaims (claim_status);

create index if not exists hospitalizationclaims_branch_idx
  on public.hospitalizationclaims (branch);

create index if not exists hospitalizationclaims_member_idx
  on public.hospitalizationclaims (member_id);

create table if not exists public.hcattachments (
  id bigint generated by default as identity primary key,
  claim_id text not null references public.hospitalizationclaims(claim_id) on delete cascade,
  file_name text not null,
  file_type text default 'application/octet-stream',
  file_size bigint default 0,
  file_data text not null,
  uploaded_by text default '',
  created_at timestamptz not null default now()
);

alter table public.hcattachments add column if not exists claim_id text;
alter table public.hcattachments add column if not exists file_name text;
alter table public.hcattachments add column if not exists file_type text default 'application/octet-stream';
alter table public.hcattachments add column if not exists file_size bigint default 0;
alter table public.hcattachments add column if not exists file_data text;
alter table public.hcattachments add column if not exists uploaded_by text default '';
alter table public.hcattachments add column if not exists created_at timestamptz default now();

create index if not exists hcattachments_claim_idx
  on public.hcattachments (claim_id);

create table if not exists public.app_settings (
  key text primary key,
  value text default '',
  updated_at timestamptz not null default now()
);

insert into public.users (
  email,
  password,
  role,
  fullname,
  position,
  branchid,
  first_login,
  must_change_password
) values (
  'admin@example.com',
  'ChangeMe123!',
  'admin',
  'Admin User',
  'System Administrator',
  '',
  true,
  true
) on conflict (email) do nothing;

insert into public.app_settings (key, value) values
  ('crsName', ''),
  ('membershipSpecialistName', ''),
  ('financeHeadName', ''),
  ('savingsCreditHeadName', ''),
  ('tellerName', ''),
  ('branchManagerName', ''),
  ('financeManagerName', ''),
  ('tellerSignatureData', ''),
  ('branchManagerSignatureData', ''),
  ('financeManagerSignatureData', ''),
  ('membershipSpecialistSignatureData', ''),
  ('financeHeadSignatureData', ''),
  ('savingsCreditHeadSignatureData', ''),
  ('reportHeaderImage', '')
on conflict (key) do nothing;

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.users to anon, authenticated;
grant select, insert, update, delete on public.members to anon, authenticated;
grant select, insert, update, delete on public.hospitals to anon, authenticated;
grant select, insert, update, delete on public.segmentation_rates to anon, authenticated;
grant select, insert, update, delete on public.hospitalizationclaims to anon, authenticated;
grant select, insert, update, delete on public.hcattachments to anon, authenticated;
grant select, insert, update, delete on public.app_settings to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
